sudo: required

services:
  - docker

before_install:
  - sudo docker-compose build
  - sudo docker ps
  - sudo docker network list    
  - sudo docker-compose up -d

script:
  - docker run --network gem-platform_default gemplatform/gem-meeting-server /bin/sh -c "PYTHONPATH=. pytest"
  - docker network list
