sudo: required

services:
  - docker

before_install:
  - sudo docker-compose build
  - sudo docker ps
  - sudo docker network list    
  - sudo docker-compose up -d
  - sudo npm install cypress -g

script:
  - docker run --network gem_default gemplatform/gem-meeting-server /bin/sh -c "PYTHONPATH=. pytest"
  - cd ./gem/tests && cypress run