sudo: required

node_js:
  - "10"

services:
  - docker

before_install:
  - npm install cypress -g
  - sudo docker-compose build 
  - sudo docker-compose up -d

script:
  - docker run --network gem_default -e TARGETS=portal:3000 -e TIMEOUT=180 waisbrot/wait
  - docker run --network gem_default meeting-server /bin/sh -c "PYTHONPATH=. pytest --disable-warnings && coveralls"
  - cd ./gem/tests && cypress run --record --key $CYPRESS