sudo: required

node_js:
  - "10"

services:
  - docker
  - nodejs

before_install:
  - sudo $(which npm) install cypress -g
  - sudo docker-compose build 
  - sudo docker-compose up -d

script:
  - docker run --network gem_default gemplatform/gem-meeting-server /bin/sh -c "PYTHONPATH=. pytest"
  - cd ./gem/tests && cypress run