sudo: required

services:
  - docker

before_install:
  - sudo docker-compose build
  - sudo docker ps
  - sudo docker-compose up -d

script:
  - docker run gemplatform/gem-meeting-server /bin/sh -c "PYTHONPATH=. pytest"
