sudo: required

node_js:
  - "10"

services:
  - docker

before_install:
  - npm install cypress -g
  - sudo docker-compose build 
  - sudo docker-compose up -d

script:
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - docker run --network gem_default -e TARGETS=portal:3000 -e TIMEOUT=180 waisbrot/wait
  - docker run $ci_env -v "$PWD/shared:/shared" --network gem_default meeting-server /bin/bash -c "env && PYTHONPATH=. pytest --cov=gms --cov-report xml:coverage.xml --disable-warnings && bash <(curl -s https://codecov.io/bash) && mv coverage.xml shared"
  - bash <(curl -s https://codecov.io/bash)
  - cd ./gem/tests && cypress run --record --key $CYPRESS