version: '3'
services:
  db:
    logging:
      driver: none

  web:
    logging:
      driver: none

  meeting-server:
    expose:
      - 9876
    ports:
      - 9876:9876
    command: python -u /usr/src/gem-server-common/_runner.py

  # office-server:
  #   command: python -u /usr/src/gem-server-common/_runner.py

  # meeting-server:
  #   command: python -u /usr/src/gem-server-common/_runner.py

  # bar-server:
  #   command: python -u /usr/src/gem-server-common/_runner.py
  