version: '3'
services:
  db:
    env_file:
      - environment.prod.env

  search:
    env_file:
      - environment.prod.env

  # Start real SMTP server
  postman:
    build: ./gem/services/postman
    restart: on-failure:5
    env_file:
      - environment.prod.env
    expose:
      - 25
      - 1025
    ports:
      - 25:25
      - 1025:1025
    volumes:
      - ./.keys/dkim:/etc/opendkim/domainkeys

  web:
    build: 
      context: ./gem/services/web
      args:
        env: prod
    env_file:
      - environment.prod.env

  chronos:
    env_file:
      - environment.prod.env

  gem-server:
    image: gem-server:latest

  meeting-server:
    env_file:
      - environment.prod.env

  media-server:
    env_file:
      - environment.prod.env

  bar-server:
    env_file:
      - environment.prod.env

  portal-server:
    env_file:
      - environment.prod.env

  office-server:
    env_file:
      - environment.prod.env

  pdf-printer:
    env_file:
      - environment.prod.env

  portal:
    env_file:
      - environment.prod.env
