version: '3'
services:
  db:
    logging:
      driver: none

  web:
    logging:
      driver: none
  
  portal-server:
    command: python -u /usr/src/gem-server-common/_runner.py

  office-server:
    command: python -u /usr/src/gem-server-common/_runner.py

  meeting-server:
    command: python -u /usr/src/gem-server-common/_runner.py
