# Start for specified environment:
# sudo GEM_ENV=staging docker-compose up -d
#
# dev is default, so for development just run:
# sudo docker-compose up

version: '3'
services:
  ##
  ## SERVICES
  ##

  # Provides MongoDB database to store
  # all the GEM data
  db:
    restart: on-failure:5
    build: ./gem/backend/db
    volumes:
      - ./.data/db:/data/db
    ports:
      - "27017:27017"
    env_file:
      - environment.${GEM_ENV-dev}.env

  search:
    restart: "no"
    build: ./gem/backend/search
    volumes:
      - ./.data/search/data:/var/lib/sphinx/data
      - ./.data/search/logs:/var/log/sphinx
    env_file:
      - environment.${GEM_ENV-dev}.env
    ports:
      - 9306:9306
      - 9312:9312
    links:
      - db:db

  # Provides NGINX web serwer to tight all
  # the web application all together in one app
  web:
    restart: on-failure:5
    build: 
      context: ./gem/backend/web
      args:
        env: ${GEM_ENV-dev}
    ports:
      - "80:80"
      - "443:443"
    links:
      - meeting-server
      - portal-server
      - office-server
      - portal
    volumes:
      - ./.data/shared/downloads:/usr/shared/downloads
      - ./.keys:/etc/nginx/ssl
    

  ##
  ## IMAGES
  ##

  # Base image for all python-based backend cantainers
  gem-server:
    image: gem-server:latest
    build: ./gem/backend/gem-server

  ##
  ## APPS: BACKEND
  ##

  # Meeting server
  meeting-server:
    image: meeting-server:latest
    restart: on-failure:5
    build: ./gem/backend/meeting
    ports:
      - "8090:8090"
    expose:
      - "8090"
    env_file:
      - environment.${GEM_ENV-dev}.env
    links:
      - db:db
    volumes:
      - ./gem/backend/meeting:/usr/src/app
    depends_on:
      - gem-server

  # Meeting server
  portal-server:
    restart: on-failure:5
    build: ./gem/backend/portal
    ports:
      - "5000:5000"
    expose:
      - "5000"
    env_file:
      - environment.${GEM_ENV-dev}.env
    links:
      - db:db
    volumes:
      - ./gem/backend/portal:/usr/src/app
    depends_on:
      - gem-server

  # Office server
  office-server:
    restart: on-failure:5
    build: ./gem/backend/office
    ports:
      - "5001:5001"
    expose:
      - "5001"
    env_file:
      - environment.${GEM_ENV-dev}.env
    links:
      - db:db
      - pdf-printer
    volumes:
      - ./gem/backend/office:/usr/src/app
      - ./.data/shared/downloads:/usr/shared/downloads
    depends_on:
      - gem-server

  # PDF Printer
  pdf-printer:
    restart: on-failure:5
    build: ./gem/backend/pdf-printer
    ports:
      - "4999:4999"
    expose:
      - "4999"

  ##
  ## APPS: FRONTEND
  #portal for meeting
  portal:
    restart: on-failure:5
    build: ./gem/frontend/portal
    command: npm run dev
    ports:
      - "3000:3000"
    expose:
      - "3000"
    links:
      - meeting-server:meeting-server
    volumes:
      - ./gem/frontend/portal:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - environment.${GEM_ENV-dev}.env