# Start for specified environment:
# sudo GEM_ENV=staging docker-compose up -d
#
# dev is default, so for development just run:
# sudo docker-compose up

version: '3'
services:
  # Meeting server
  meeting-server:
    volumes:
      - meeting-server-sync:/usr/src/app:nocopy

  # Meeting server
  portal-server:
    volumes:
      - ./gem/services/portal:/usr/src/app

  # Web client for meeting
  portal:
    volumes:
      - ./gem/frontend/portal:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  portal-sync:
    external: true

  meeting-server-sync:
    external: true
