version: '3'
services:
  ##
  ## SERVICES
  ##

  # Provides MongoDB database to store
  # all the GEM data
  gem-database:
    image: gemplatform/gem-database
    restart: always
    build: ./gem/backend/gem-database
    volumes:
      - ./.data/db:/data/db
    ports:
      - "27017:27017"
    env_file:
      - environment.${GEM_ENV-dev}.env

  gem-elastic-search:
    image: gemplatform/gem-elastic-search
    restart: "no"
    build: ./gem/backend/gem-elastic-search
    env_file:
      - environment.${GEM_ENV-dev}.env
    volumes:
      - ./.data/es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  # Provides NGINX web serwer to tight all
  # the web application all together in one app
  gem-web:
    image: gemplatform/gem-web
    restart: always
    build: 
      context: ./gem/frontend/gem-web
      args:
        env: ${GEM_ENV-dev}
    ports:
      - "80:80"
      - "443:443"
    links:
      - gem-meeting-server:gem-meeting-server
      - gem-portal-client:gem-portal-client
      - gem-portal-server:gem-portal-server
    

  ##
  ## IMAGES
  ##

  # Base image for all python-based backend cantainers
  gem-server:
    image: gemplatform/gem-server
    build: ./gem/backend/gem-server-common

  ##
  ## APPS: BACKEND
  ##

  # Meeting server
  gem-meeting-server:
    image: gemplatform/gem-meeting-server
    restart: always
    build: ./gem/backend/gem-meeting-server
    ports:
      - "8090:8090"
    expose:
      - "8090"
    env_file:
      - environment.${GEM_ENV-dev}.env
    links:
      - gem-database:gem-database
    volumes:
      - ./gem/backend/gem-meeting-server:/usr/src/app

  # Meeting server
  gem-portal-server:
    image: gemplatform/gem-portal-server
    restart: always
    build: ./gem/backend/gem-portal-server
    ports:
      - "5000:5000"
    expose:
      - "5000"
    env_file:
      - environment.${GEM_ENV-dev}.env
    links:
      - gem-database:gem-database
    volumes:
      - ./gem/backend/gem-portal-server:/usr/src/app

  ##
  ## APPS: FRONTEND
  ##

  # Web client for meeting
  gem-portal-client:
    image: gemplatform/gem-portal-client
    restart: always
    build: ./gem/frontend/gem-portal
    command: npm run dev
    ports:
      - "3000:3000"
    expose:
      - "3000"
    links:
      - gem-meeting-server:gem-meeting-server
    volumes:
      - ./gem/frontend/gem-portal:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - environment.${GEM_ENV-dev}.env
