# Start for specified environment:
# sudo GEM_ENV=staging docker-compose up -d
#
# dev is default, so for development just run:
# sudo docker-compose up

version: '3'
services:
  # Meeting server
  gem-meeting-server:
    volumes:
      - gem-meeting-server-sync:/usr/src/app:nocopy

  # Meeting server
  gem-portal-server:
    volumes:
      - ./gem/backend/gem-portal-server:/usr/src/app

  # Web client for meeting
  gem-portal-client:
    volumes:
      - ./gem/frontend/gem-portal:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  gem-portal-client-sync:
    external: true

  gem-meeting-server-sync:
    external: true
