version: '3'
services:
  db:
    # switch logging off
    logging:
      driver: none

  web:
    # switch logging off
    logging:
      driver: none

  # Enable debugging for meeting server
  meeting-server:
    expose:
      - 9876
    ports:
      - 9876:9876
    command: python -u /usr/src/gem-server-common/_runner.py
