version: '3'
services:
  db:
    env_file:
      - environment.staging.env

  search:
    env_file:
      - environment.staging.env

  postman:
    env_file:
      - environment.staging.env

  web:
    build: 
      context: ./gem/services/web
      args:
        env: staging
    env_file:
      - environment.staging.env

  chronos:
    env_file:
      - environment.staging.env

  gem-server:
    image: gem-server:latest

  meeting-server:
    env_file:
      - environment.staging.env

  media-server:
    env_file:
      - environment.staging.env

  bar-server:
    env_file:
      - environment.staging.env

  portal-server:
    env_file:
      - environment.staging.env

  office-server:
    env_file:
      - environment.staging.env

  pdf-printer:
    env_file:
      - environment.staging.env

  portal:
    env_file:
      - environment.staging.env
